baseurl = "https://ivahaev.ru/"
languageCode = "ru-RU"
title = "ivahaev.ru"
copyright = "2022 Евгений Иваха"
disqusShortname = "ivahaev"
publishdir = "docs"

contentdir = "content"
layoutdir = "layouts"
canonifyurls = true
MetaDataFormat = "toml"
paginate = 10

[indexes]
    category = "categories"
    tag = "tags"
[author]
    name = "ivahaev"

[params]
    date_format = "02.01.2006"